sudo: required
services:
  - docker

before_install:
  - docker build -t paul/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run paul/react-test npm test -- --coverage

after_success:
  - docker build -t paul/multi-client ./client
  - docker build -t paul/multi-nginx ./nginx
  - docker build -t paul/multi-server ./server
  - docker build -t paul/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push paul/multi-client
  - docker push paul/multi-nginx
  - docker push paul/multi-server
  - docker push paul/multi-worker


