sudo: required
services:
  - docker

before_install:
  - docker build -t paul/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run paul/react-test npm test -- --coverage

after_success:
  - docker build -t paulg92/multi-client ./client
  - docker build -t paulg92/multi-nginx ./nginx
  - docker build -t paulg92/multi-server ./server
  - docker build -t paulg92/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push paulg92/multi-client
  - docker push paulg92/multi-nginx
  - docker push paulg92/multi-server
  - docker push paulg92/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: eu-west-3
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-950672890849
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id:  $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY


